import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Define our complete token structure
const defaultTokenStructure = {
  type: 'bezier',
  duration: '300ms',
  delay: '0ms',
  easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
  opacityFrom: '0',
  opacityTo: '1',
  scaleFrom: '1',
  scaleTo: '1',
  rotateFrom: '0deg',
  rotateTo: '0deg',
  translateFrom: '0px',
  translateTo: '0px',
  stiffness: 100,
  damping: 10,
  mass: 1,
  velocity: 0
};

function resolveTokenReference(value, coreTokens) {
  // Handle invalid values
  if (!value || value === 'NaN' || (typeof value === 'string' && value.includes('NaN'))) {
    return undefined;  // This will trigger the default value
  }
  
  if (typeof value !== 'string') return value;
  
  // If it's a direct value with units (e.g., "1.15" or "5deg" or "16px")
  if (!value.startsWith('{')) {
    return value;
  }
  
  const match = value.match(/^{(.+)}$/);
  if (!match) return value;
  
  const coreToken = coreTokens[match[1]]?.value;
  return coreToken || value;
}

function normalizeTokenValue(value, coreTokens) {
  console.log('Input value:', JSON.stringify(value, null, 2));

  // If it's a string reference
  if (typeof value === 'string') {
    return resolveTokenReference(value, coreTokens);
  }

  // If it has a value property that's a string (reference)
  if (value?.value && typeof value.value === 'string') {
    return resolveTokenReference(value.value, coreTokens);
  }

  // Get the actual value object to normalize
  const valueToNormalize = value?.value || value || {};

  // Always return a complete token structure
  const normalized = {
    type: valueToNormalize.type || 'bezier',
    duration: resolveTokenReference(valueToNormalize.duration, coreTokens) || '300ms',
    delay: resolveTokenReference(valueToNormalize.delay, coreTokens) || '0ms',
    easing: resolveTokenReference(valueToNormalize.easing, coreTokens) || 'cubic-bezier(0.4, 0, 0.2, 1)',
    opacityFrom: resolveTokenReference(valueToNormalize.opacityFrom, coreTokens) || '1',
    opacityTo: resolveTokenReference(valueToNormalize.opacityTo, coreTokens) || '1',
    scaleFrom: resolveTokenReference(valueToNormalize.scaleFrom, coreTokens) || '1',
    scaleTo: resolveTokenReference(valueToNormalize.scaleTo, coreTokens) || '1',
    rotateFrom: resolveTokenReference(valueToNormalize.rotateFrom, coreTokens) || '0deg',
    rotateTo: resolveTokenReference(valueToNormalize.rotateTo, coreTokens) || '0deg',
    translateFrom: resolveTokenReference(valueToNormalize.translateFrom, coreTokens) || '0px',
    translateTo: resolveTokenReference(valueToNormalize.translateTo, coreTokens) || '0px',
    stiffness: valueToNormalize.stiffness || 100,
    damping: valueToNormalize.damping || 10,
    mass: valueToNormalize.mass || 1,
    velocity: valueToNormalize.velocity || 0
  };

  console.log('Normalized token:', JSON.stringify(normalized, null, 2));
  return normalized;
}

function normalizeTokens(tokens, coreTokens) {
  return {
    patterns: tokens.patterns ? Object.entries(tokens.patterns).reduce((acc, [name, pattern]) => {
      acc[name] = {
        value: normalizeTokenValue(pattern.value, coreTokens),
        type: pattern.type || 'bezier',
        description: pattern.description || ''
      };
      return acc;
    }, {}) : {},
    components: tokens.components ? Object.entries(tokens.components).reduce((acc, [name, component]) => {
      acc[name] = {
        value: normalizeTokenValue(component.value, coreTokens),
        type: component.type || 'bezier',
        description: component.description || ''
      };
      return acc;
    }, {}) : {}
  };
}

// Generate TypeScript type definitions
function generateTypeDefinitions(tokens) {
  return `// Generated by build-tokens.js
export interface TokenValue {
  type: 'bezier' | 'spring';
  duration: string;
  delay: string;
  easing: string;
  opacityFrom: string;
  opacityTo: string;
  scaleFrom: string;
  scaleTo: string;
  rotateFrom: string;
  rotateTo: string;
  translateFrom: string;
  translateTo: string;
  stiffness?: number;
  damping?: number;
  mass?: number;
  velocity?: number;
}

export interface AnimationPattern {
  value: TokenValue;
  type: string;
  description: string;
}

export interface MotionToken {
  patterns: {
    [key: string]: AnimationPattern;
  };
  components: {
    [key: string]: AnimationPattern;
  };
}

export const motionTokens: {
  aeroglobal: MotionToken;
  branda: MotionToken;
} = {
  aeroglobal: {
    patterns: ${JSON.stringify(tokens.aeroglobal.patterns, null, 2)},
    components: ${JSON.stringify(tokens.aeroglobal.components, null, 2)}
  },
  branda: {
    patterns: ${JSON.stringify(tokens.branda.patterns, null, 2)},
    components: ${JSON.stringify(tokens.branda.components, null, 2)}
  }
} as const;

export type MotionTokens = typeof motionTokens;
`;
}

function processTokenValue(token, tokens, coreTokens) {
  // If token is a direct value
  if (typeof token === 'string') {
    if (token.startsWith('{')) {
      const reference = token.match(/{([^}]+)}/)[1];
      const [category, property] = reference.split('.');
      const resolvedToken = tokens[category]?.[property];
      
      // If the resolved token has extensions (like alpha)
      if (resolvedToken?.$extensions?.['studio.tokens']?.modify) {
        return processTokenValue(resolvedToken, tokens, coreTokens);
      }
      
      return resolvedToken?.value || token;
    }
    return token;
  }

  // If token has extensions (like shadow with alpha)
  if (token.$extensions?.['studio.tokens']?.modify) {
    const modify = token.$extensions['studio.tokens'].modify;
    if (modify.type === 'alpha') {
      const baseColor = typeof token.value === 'string' && token.value.startsWith('{')
        ? processTokenValue(token.value, tokens, coreTokens)
        : token.value;

      if (baseColor.startsWith('#')) {
        const r = parseInt(baseColor.slice(1, 3), 16);
        const g = parseInt(baseColor.slice(3, 5), 16);
        const b = parseInt(baseColor.slice(5, 7), 16);
        return `rgba(${r}, ${g}, ${b}, ${modify.value})`;
      }
    }
  }

  // If token has a value property
  if (token.value) {
    return processTokenValue(token.value, tokens, coreTokens);
  }

  return token;
}

function generateCssVariables(tokens, coreTokens) {
  const vars = [];
  
  // Process color tokens
  if (tokens.color) {
    Object.entries(tokens.color).forEach(([key, value]) => {
      if (typeof value === 'object' && value !== null) {
        if (Object.keys(value).length > 0 && !value.value) {
          Object.entries(value).forEach(([subKey, subValue]) => {
            const resolvedValue = processTokenValue(subValue, tokens, coreTokens);
            vars.push(`  --color-${key}-${subKey}: ${resolvedValue};`);
          });
        } else {
          const resolvedValue = processTokenValue(value, tokens, coreTokens);
          vars.push(`  --color-${key}: ${resolvedValue};`);
        }
      }
    });
  }

  // Handle shadow tokens
  if (tokens.shadow) {
    Object.entries(tokens.shadow).forEach(([key, value]) => {
      if (value.value && typeof value.value === 'object') {
        const shadowColor = processTokenValue(value.value.color, tokens, coreTokens);
        const shadowValue = `${value.value.x} ${value.value.y} ${value.value.blur} ${value.value.spread} ${shadowColor}`;
        vars.push(`  --shadow-${key}: ${shadowValue};`);
      }
    });
  }

  // Handle border tokens
  if (tokens.border?.radius) {
    Object.entries(tokens.border.radius).forEach(([key, value]) => {
      vars.push(`  --border-radius-${key}: ${value.value};`);
    });
  }

  return vars;
}

async function main() {
  try {
    // Load the token files
    const brandaTokens = JSON.parse(
      await fs.readFile(path.join(__dirname, 'src/tokens/Origin/Source/Branda.json'), 'utf8')
    );
    const aeroglobalTokens = JSON.parse(
      await fs.readFile(path.join(__dirname, 'src/tokens/Origin/Source/Aeroglobal.json'), 'utf8')
    );
    const coreTokens = JSON.parse(
      await fs.readFile(path.join(__dirname, 'src/tokens/Origin/Source/Core.json'), 'utf8')
    );
    // Load themes configuration
    const themes = JSON.parse(
      await fs.readFile(path.join(__dirname, 'src/tokens/Origin/$themes.json'), 'utf8')
    );

    // Generate core values from Core.json
    const generatedCoreValues = Object.entries(coreTokens).reduce((acc, [key, token]) => {
      acc[key] = token.value;
      return acc;
    }, {});

    const tokens = {
      branda: normalizeTokens(brandaTokens, coreTokens),
      aeroglobal: normalizeTokens(aeroglobalTokens, coreTokens)
    };
    
    // Product theme CSS is maintained manually in src/styles/{aeroglobal,branda}.css
    // (Folio / Nocturne bookstore imprints — not regenerated from token JSON).
    
    // Generate the TypeScript file with both motionTokens and coreValues
    const typeScriptContent = `// Generated by build-tokens.js
${generateTypeDefinitions(tokens)}

export const coreValues = ${JSON.stringify(generatedCoreValues, null, 2)};
`;

    await fs.writeFile(
      path.join(process.cwd(), 'src/tokens/generated/motion.generated.ts'),
      typeScriptContent
    );
    
    console.log('✅ Tokens built successfully!');
  } catch (error) {
    console.error('❌ Error building tokens:', error);
    process.exit(1);
  }
}

main();
